# Generated by Django 5.0.6 on 2024-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0002_remove_produto_categoria_remove_imagem_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
                ('quantidade', models.FloatField()),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('total', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
