# Generated by Django 5.0.6 on 2024-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
