# Generated by Django 5.0.6 on 2024-05-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_venda_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='nome',
        ),
    ]
