# Generated by Django 5.0.6 on 2024-05-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontocoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
            ],
        ),
    ]
