# Generated by Django 5.0.6 on 2024-05-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0003_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
